### ISSUE TITLE
Green Dots test suite failing to run on current HEAD (0c00be1)

### ISSUE THREAD

**Issue by brandondrew** [phlex-ruby/phlex#640]
I believe this says it all:

```
brandon@Air phlex % git switch 0c00be1
fatal: a branch is expected, got commit '0c00be1'
hint: If you want to detach HEAD at the commit, try again with the --detach option.
brandon@Air phlex % bundle exec gd gd 
bundler: failed to load command: gd (/Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/gd)
gd/phlex/callable.rb:4:in `<class:Example>': uninitialized constant Phlex::Callable (NameError)
	from gd/phlex/callable.rb:3:in `block (2 levels) in <top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/green_dots-6aa5a700a46c/exe/gd:20:in `class_eval'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/green_dots-6aa5a700a46c/exe/gd:20:in `block (2 levels) in <top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/green_dots-6aa5a700a46c/exe/gd:19:in `initialize'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/green_dots-6aa5a700a46c/exe/gd:19:in `new'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/green_dots-6aa5a700a46c/exe/gd:19:in `block in <top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/green_dots-6aa5a700a46c/exe/gd:18:in `each'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/green_dots-6aa5a700a46c/exe/gd:18:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/gd:25:in `load'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/gd:25:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:451:in `exec'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/brandon/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
brandon@Air phlex % bundle exec gd   
bundler: failed to load command: gd (/Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/gd)
<internal:/Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- helper (LoadError)
	from <internal:/Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/green_dots-6aa5a700a46c/exe/gd:12:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/gd:25:in `load'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/gd:25:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:451:in `exec'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/brandon/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
brandon@Air phlex % bundler --version
Bundler version 2.5.5
brandon@Air phlex % gem --version
3.5.5
brandon@Air phlex % ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]
brandon@Air phlex % rbenv --version
rbenv 1.2.0
```

I've never used Green Dots before so I wasn't sure if the repetition of `gd` was correct, or a typo in the source I was working from, so I tried it both ways.

I have not yet tried bisecting.  I'll try that later if time allows...

**Comment by joeldrapper** [comment]
Let's ignore GreenDots for now and just use `bundle exec sus`. I don't think there are any GreenDots tests that aren't covered by the Sus suite, but I’ll double-check before I close this issue.
