### ISSUE TITLE
defs is missing from svg

### ISSUE THREAD

**Issue by konung** [phlex-ruby/phlex#813]
Hit an error while trying to generate this svg. 

`defs` is a valid svg tag https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs

```ruby
web    | NoMethodError (undefined method `defs' 
web    |
web    | app/views/base.rb:68:in `block in background_svg'
web    | app/views/base.rb:67:in `background_svg'
web    | app/views/base.rb:29:in `block (4 levels) in around_template'
web    | app/views/base.rb:28:in `block (3 levels) in around_template'
web    | app/views/base.rb:27:in `block (2 levels) in around_template'
web    | app/views/base.rb:23:in `block in around_template'
web    | app/views/base.rb:20:in `around_template'

```

```ruby
    svg class: "absolute inset-0 -z-10 hidden h-full w-full stroke-gray-200 sm:block [mask-image:radial-gradient(64rem_64rem_at_top,white,transparent)]", "aria-hidden": "true" do
      defs do
        pattern id: "55d3d46d-692e-45f2-becd-d8bdc9344f45", x: "50%", y: "0", width: "200", height: "200", patternUnits: "userSpaceOnUse" do
          path d: "M.5 200V.5H200", fill: "none"
        end
      end
      svg x: "50%", y: "0", class: "overflow-visible fill-gray-50" do
        path d: "M-200.5 0h201v201h-201Z M599.5 0h201v201h-201Z M399.5 400h201v201h-201Z M-400.5 600h201v201h-201Z", "stroke-width": "0"
      end
      rect width: "100%", height: "100%", "stroke-width": "0", fill: "url(#55d3d46d-692e-45f2-becd-d8bdc9344f45)"
    end

```

**Comment by konung** [comment]
Found #38. 

Thought I needed to register custom elements. 


```
  register_element :defs
  register_element :pattern
```


Then realized after reading code a bit more , this is easily solved by simply including  in my Views::Base 

```
 
 include Phlex::SVG::StandardElements

```

**Comment by konung** [comment]
Thanks for the tip Joel! And thank you for Phlex!
